from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Mapping

from .io import Phase1Artifacts


@dataclass(frozen=True)
class PaperParameters:
    a: float
    alpha: float
    beta: float
    gamma: float
    epsilon: float
    tau: float


class Phase2Model:
    """Thin model wrapper around the Phase-1 generated proof graph.

    This class intentionally exposes semantic operations rather than a solver
    backend.  Paper Replay uses these constraints deterministically.  The same
    object can later feed LP/NLP/MILP solvers.
    """

    def __init__(self, artifacts: Phase1Artifacts):
        self.artifacts = artifacts
        self.manifest = artifacts.manifest
        self.flow = artifacts.flow

        self.alias_map: Dict[str, str] = dict(self.flow["alias_map"])
        self.reverse_alias_map: Dict[str, str] = {
            state_id: alias for alias, state_id in self.alias_map.items()
        }
        self.sources = {
            x["name"]: x for x in self.flow["sources"]
        }
        self.rewrite_rules = {
            x["name"]: x for x in self.flow["linear_rewrite_rules"]
        }
        self.bundle_rules = {
            x["name"]: x for x in self.flow["bundle_rules"]
        }

    @property
    def reference_parameters(self) -> PaperParameters:
        p = self.manifest["reference_point"]
        return PaperParameters(
            a=float(p["a"]),
            alpha=float(p["alpha"]),
            beta=float(p["beta"]),
            gamma=float(p["gamma"]),
            epsilon=float(p["epsilon"]),
            tau=float(p["tau"]),
        )

    def alias(self, paper_name: str) -> str:
        return self.alias_map.get(paper_name, paper_name)

    def paper_name(self, resource: str) -> str:
        return self.reverse_alias_map.get(resource, resource)

    def source(self, name: str) -> Mapping:
        return self.sources[name]

    def rewrite(self, name: str) -> Mapping:
        return self.rewrite_rules[name]

    def bundle(self, name: str) -> Mapping:
        return self.bundle_rules[name]

    def check_reference_parameter_constraints(self) -> List[str]:
        """Explicit checks for Proposition 4.3 at the Phase-1 reference point."""
        p = self.reference_parameters
        failures = []

        if not (1.5 + 3*p.epsilon < p.a < 2):
            failures.append("1.5+3epsilon < a < 2")
        tau_expected = (p.a - 1.0) / p.a - p.epsilon
        if abs(p.tau - tau_expected) > 5e-12:
            failures.append("tau=(a-1)/a-epsilon")
        if not (1/18 < p.alpha < p.beta):
            failures.append("1/18 < alpha < beta")
        if not (p.beta < (1 - 3*p.beta) / 3):
            failures.append("beta < (1-3beta)/3")
        if not ((1 - 3*p.beta)/3 < p.gamma < 1/3):
            failures.append("(1-3beta)/3 < gamma < 1/3")
        if not (1/3 < p.tau):
            failures.append("1/3 < tau")
        return failures

    def expected_prop43_coefficients(self) -> Dict[str, float]:
        """Read the regression target generated by Phase 1."""
        cert = self.manifest["reference_final_certificate"]
        return {
            self.alias(name): float(coeff)
            for name, coeff in cert["terms"].items()
        }
